import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("cleaned_titanic.csv")
plt.figure()
sns.countplot(x="Survived", data=df)
plt.title("Titanic Survival Count")
plt.xlabel("Survived (0 = No, 1 = Yes)")
plt.ylabel("Number of Passengers")
plt.show()
plt.figure()
sns.countplot(x="Sex", hue="Survived", data=df)
plt.title("Survival by Gender")
plt.xlabel("Gender")
plt.ylabel("Number of Passengers")
plt.show()
plt.figure()
sns.countplot(x="Pclass", data=df)
plt.title("Passengers by Class")
plt.xlabel("Passenger Class")
plt.ylabel("Number of Passengers")
plt.show()
plt.figure()
plt.hist(df["Age"].dropna(), bins=20)
plt.title("Age Distribution of Passengers")
plt.xlabel("Age")
plt.ylabel("Number of Passengers")
plt.show()
plt.figure()
plt.scatter(df["Age"], df["Fare"])
plt.title("Fare vs Age")
plt.xlabel("Age")
plt.ylabel("Fare")
plt.show()